### ISSUE TITLE
w3m can't load many web pages anymore, e.g. google.com

### ISSUE THREAD

**Issue by Nithilher** [tats/w3m#206] opened 2021-11-23 21:39 UTC
I use the stable version of w3m.
Since a few days, it stopped working properly. It gets stuck when I try to open pages like google.com. It says "Opening socket..." for ever, I have to kill it with CTRL-C. It then says "w3m: Can't load google.com".

I tried your branch, as it is listed as head branch in homebrew. I can compile it, but it shows the exact same behavior. 

Many web pages work, but a lot do not work, like: google.com, apple.com, nasa.gov, ...

Does anybody else have the same problem?

macOS BigSur 11.6.1 with homebrew, w3m/0.5.3+git20200502

**Comment by Boruch-Baum** [comment] 2021-11-23 23:04
On 2021-11-23 21:39, Nithilher wrote:
>    ...
>    Many web pages work, but a lot do not work, like: google.com,
>    apple.com, nasa.gov, ...
>
>    Does anybody else have the same problem?

I can't reproduce this for google or apple. The nasa site doesn't load
with w3m, but I don't think it ever did, did it? It's JS-heavy?

My first suggestion is check your DNS. Try the equivalent of
  $ nslookup google.com

My second suggestion is to report back whether you can access those
sites using another browser, if you have access to one.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Nithilher** [comment] 2021-11-24 07:13
I can access google.com with any other browser, e.g. links, google chrome, safari. That is why I wondered. Only thing which changed on my system was a system update to the latest version of BigSur (I am not yet on Monterey).

**Comment by Nithilher** [comment] 2021-11-24 08:22
> On 2021-11-23 21:39, Nithilher wrote: ... Many web pages work, but a lot do not work, like: google.com, apple.com, nasa.gov, ... Does anybody else have the same problem?
> I can't reproduce this for google or apple. The nasa site doesn't load with w3m, but I don't think it ever did, did it? It's JS-heavy? My first suggestion is check your DNS. Try the equivalent of $ nslookup google.com My second suggestion is to report back whether you can access those sites using another browser, if you have access to one.
> […](#)
> -- hkp://keys.gnupg.net CA45 09B5 5351 7C11 A9D1 7286 0036 9E45 1595 8BC0

I can access google.com with any other browser, e.g. links, google chrome, safari. That is why I wondered. Only thing which changed on my system was a system update to the latest version of BigSur (I am not yet on Monterey).

**Comment by xereeto** [comment] 2022-03-08 03:48
Seconding this. Same problem Mac Monterey M1.

**Comment by rkta** [comment] 2022-03-08 08:54
On Tue, Nov 23, 2021 at 11:13:27PM -0800, Nithilher wrote:
> I can access google.com with any other browser, e.g. links, google chrome, safari. That is why I wondered. Only thing which changed on my system was a system update to the latest version of BigSur (I am not yet on Monterey).

Does it make any difference if you use http://google.com ,
http://www.google.com or https://www.google.com ?

**Comment by tats** [comment] 2023-01-18 22:33
Type `w3m -version` to see the build options, "ssl" is required if
you'd like to open HTTPS pages.

Use the configure option --with-ssl to specify the location of OpenSSL.
e.g. `./configure --with-ssl=/usr/local/opt/openssl@1.1`

Closing.

**Closed by tats** 2023-01-18 22:33 UTC

**Comment by meksrc** [comment] 2023-02-09 09:14
Hey guys, also have a m1 mac and pages on lynx or w3m wont load for me :( somebody found a solution?
