### ISSUE TITLE
Hyphens inserted in the middle of words on some terminals

### ISSUE THREAD

**Issue by lucabol** [tats/w3m#258] opened 2022-12-26 08:48 UTC
This is a fun one ...

When opening pages on my blog (i.e. https://www.lucabol.com/posts/2022-03-09-using-zig-comptime-for-conceptual-dryness/) on some terminals many words have either hyphens in them or empty spaces cutting the words in multiple parts.

Neither Lynx, Chrome or Firefox or any other program exposes this behavior. Looking at the source of the web page in w3m, I see the hyphens. Looking at the source in other browsers, I don't. When I copy and paste the words with hyphens from the terminals, the pasted text doesn't have the hyphens.

I am on Ubuntu 20.03 under WSL2. On mintty I see hyphens, on Windows Terminal I see empty spaces instead of hyphens, on WezTerm it works just fine.

Example from mintty. In Windows Terminal there are spaces instead of hyphens.

````
While writ­-ing my C# Forth, I grew un­-happy about the con­-cep­-tual.
````

**Comment by N-R-K** [comment] 2022-12-26 08:54
Duplicate of https://github.com/tats/w3m/issues/224 ?

**Comment by lucabol** [comment] 2022-12-26 09:24
I don't see soft hypens in the source code for the page I refer to, but perhaps I miss something.

**Comment by rkta** [comment] 2022-12-26 11:51
On Mon, Dec 26, 2022 at 12:54:21AM -0800, N-R-K wrote:
> Duplicate of https://github.com/tats/w3m/issues/224 ?

Kind of, both are about soft hyphens. The web site mentioned here uses
Unicode soft hyphens.

Works for me with https://github.com/tats/w3m/pull/256 applied.

**Comment by tats** [comment] 2023-01-06 10:47
Fixed by https://github.com/tats/w3m/pull/256

**Closed by tats** 2023-01-06 10:47 UTC
